# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a3dad532adcd61d02c3832e006b0ec1ce6399cb431dc609d649b9a53bd44ad395964c09582d35efd411bc227f4fd092aa73c5cd5476b9e574b746d3c89babd2a

test:
  secret_key_base: 543d6ccbe676f8534ba99bb6f4af2008279989a407696d7b7b6e49e6b1d3be726c8aeb0b8c1bf143512ee16fd4f7f701baa20ccb2f6f083e9479e1900118f6e9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
